Import('*')

if env['TARGET_ISA'] == 'no':
    Return()

env.Append(CPPPATH=Dir('../../../../../src/core/'))
env.Append(CPPPATH=Dir('../../../../../build/src/core/'))

env.Append(LIBPATH=Dir('../../../../../build/lib/'))
env.Append(LIBS=['sal', 'comm', 'cpn', 'efw', 'util', 'pcl', 'hsc-simple'])


SimObject('FailGem5Device.py')
Source('FailGem5Device.cc')
DebugFlag('Fail')
