Import('*')

if env['TARGET_ISA'] == 'no':
    Return()

env.Prepend(CPPPATH=Dir('../../../../../src/core/'))
env.Prepend(CPPPATH=Dir('../../../../../build/src/core/'))

env.Prepend(LIBPATH=Dir('../../../../../build/lib/'))
gStaticLibs = ['-lfail-sal', '-lfail-hsc-simple', '-lfail-comm', '-lfail-cpn', '-lfail-efw', '-lfail-util', '-lpcl']

if (len(gStaticLibs)>0):
	linkFlags = ['-Wl,--start-group']
	linkFlags = linkFlags+gStaticLibs
	linkFlags = linkFlags+['-Wl,--end-group']

	env['GEN_LIB_BUILD_STATIC'] = linkFlags

	env.Append(SHLINKCOM = ' $GEN_LIB_BUILD_STATIC')
	env.Append(LINKCOM = ' $GEN_LIB_BUILD_STATIC')


SimObject('FailGem5Device.py')
Source('FailGem5Device.cc')
DebugFlag('Fail')
